// jtpc#0103.cs: FCL ile ilgili kýsa açýklamalar örneði.

using System;
namespace AðÝskeleti {
    class FCL {
        static void Main() {
            Console.Write (".NET FCL (FrameworkClassLibrary/ÝskeletSýnýfKütüphanesi) C# uygulamalarýnda kullanýlan sýnýflar, aduzamlarý, arayüzler ve deðer tipleri koleksiyonudur.\nÝçerdiði binlerce sýnýf C#'ýn þu fonksiyonlarýný temin eder: temel ve kullanýcý-tanýmlý veri tipleri; istisna yönetimine destek; girdi/çýktý ve akýþ iþlemleri; alttaki sistemle iletiþim; veriye eriþim; win-temelli GUI/GraphicslUserInterface/GrafikKullanýcýArayüz uygulamalarý yaratýr; að-müþterisi ve sunucu uygulamalarý yaratýr; að servisleri yaratým desteði.\nFCL'de tanýmlý enönemli sýnýf ve arayüzleri kapsayan aduzamlarý þunlardýr: System; System.Data, System.Data.Common, System.Data.OleDb, System.Data.SqlClient, System.Data.SqlTypes; System.IO, System.DirectoryServices, System.IO.IsolatedStorage; System.Diagnostics; System.Net, System.Net.Sockets; System.Windows.Forms, System.Windows.Forms.Design; System.Web, System.WebCaching, System.Web.UI, System.Web.UI.Design, System.Web.UI.WebControls, System.Web.UI.HtmlControls, System.Web.Configuration, System.Web.Hosting, System.Web.Mail, System.Web.SessionState; System.Web.Services, System.Web.Services.Description, System.Web.Services.Configuration, System.Web.Services.Discovery, System.Web.Services.Protocols; System.Security, System.Security.Permissions, System.Security.Policy, System.WebSecurity, System.Security.Cryptography; System.Xml, System.Xml.Schema, System.Xml.Serialization, System.Xml.XPath, System.Xml.Xsl\n.NET Framework'ün alt parçasý olan .NET BCL (BaseClassLibrary/TemelSýnýfKütüphanesi þu aduzamlardan müteþþekkildir: System.Collections, System.Configuration, System.Diagnostics, System.Globalization, System.IO, System.Net, System.Reflection, System.Resources, System.Security, System.ServiceProcess, System.Text, System.Threading, System.Runtime, System.InteropServices, System.Remoting, System.Serialization, System.Data, System.Xml, System.Web, System.Drawing ve System.windows.Form\nTuþ..."); Console.ReadKey(); Console.WriteLine ("\n");
        }
    }
}